# Generated by Django 2.0.7 on 2018-07-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 1, 29, 33, 617701))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 1, 29, 33, 617734))),
            ],
            options={
                'db_table': 'subscribes',
                'managed': False,
            },
        ),
    ]
