# Generated by Django 2.0.7 on 2018-07-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='auth_user',
        ),
    ]
