# Generated by Django 2.0.7 on 2018-07-10 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20180709_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 7, 10, 19, 54, 44, 816353))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 7, 10, 19, 54, 44, 816385))),
            ],
            options={
                'db_table': 'subscribes',
                'managed': False,
            },
        ),
    ]
